# Generated by Django 4.1.7 on 2023-03-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Feeding Date')),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default=('B', 'Breakfast'), max_length=1)),
                ('bunny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bunny')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
