# Generated by Django 4.1.7 on 2023-03-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feedeing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedeing',
            new_name='Feeding',
        ),
    ]
