# Generated by Django 4.1.7 on 2023-03-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunny',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
